---
.travis.yml:
  docker_sets:

appveyor.yml:
  delete: true

Gemfile:
  optional:
    ':development':
      - gem: 'rspec-puppet'
    ':development':
      - gem: 'puppet-resource_api'


MAINTAINERS.md:
  delete: true

NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2014
      end: 'latest'

spec/acceptance/nodesets/centos-7-x64.yml:
  delete: true
spec/acceptance/nodesets/debian-8-x64.yml:
  delete: true
spec/acceptance/nodesets/default.yml:
  delete: true
spec/acceptance/nodesets/docker/centos-7.yml:
  delete: true
spec/acceptance/nodesets/docker/debian-8.yml:
  delete: true
spec/acceptance/nodesets/docker/ubuntu-14.04.yml:
  delete: true
